import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { animatedArtwork, doorwayArtwork } from './artwork.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const versioned = file => `${file}?v=${createHash('sha256').update(readFileSync(path.join(root, 'dist', file))).digest('hex').slice(0, 12)}`;
const c = JSON.parse(readFileSync(path.join(root, 'ui_copy.json'), 'utf8'));
const e = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const sectionHeading = (eyebrow, heading) => `<p class="eyebrow">${e(eyebrow)}</p><h2>${e(heading)}</h2>`;
const art = (b, eager = false) => `<a class="art-link" href="assets/${e(b.image)}" data-art aria-label="${e(c.library.artLabel)}: ${e(b.title)}"><img src="assets/${e(b.image)}" alt="${e(b.alt)}" width="1536" height="1024" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'}></a>`;
const companionArt = (key, animated = false, inline = false) => {
  const b = c.companions[key];
  const tag = inline ? 'span' : 'div';
  const portrait = key === 'readers' || key === 'creators';
  return `<${tag} class="companion companion-${key}" ${animated ? 'data-artwork="companion"' : ''}><a class="art-link ${animated ? 'art-stage' : ''}" href="assets/${e(b.image)}" data-art aria-label="${e(c.library.artLabel)}: ${e(b.title)}"><img ${animated ? 'class="art-companion"' : ''} src="assets/${e(b.image)}" alt="${e(b.alt)}" width="${portrait ? 700 : animated ? 640 : 1200}" height="${portrait ? 1050 : animated ? 640 : 800}" loading="lazy"></a></${tag}>`;
};
const doorBookOrder = [1, 0, 2];
const doorLink = (i, hotspot = false) => `<a href="#${e(c.books[i].id)}" class="${hotspot ? `door-hotspot door-${i}` : 'door-label'}" data-world="${i}" ${hotspot ? 'tabindex="-1" aria-hidden="true"' : `aria-controls="world-preview"`}><span>${e(c.explore.doorLabels[i])}</span><span aria-hidden="true">↗</span></a>`;
const doorArt = `<figure class="hero-art door-stage" data-artwork="doorways"><div class="door-picture art-stage">${doorwayArtwork(c,e)}${doorBookOrder.map(i=>doorLink(i,true)).join('')}</div><figcaption>${e(c.explore.prompt)}</figcaption><nav class="door-labels" aria-label="${e(c.explore.doorsLabel)}">${doorBookOrder.map(i=>doorLink(i)).join('')}</nav><button class="art-replay text-button" data-art-replay hidden>${e(c.explore.replayDoors)} <span aria-hidden="true">↻</span></button></figure>`;
const worldPreview = `<div id="world-preview" class="world-preview" hidden>${c.books.map((b,i)=>`<section class="world-selection theme-${e(b.id)}" data-world-panel="${i}" aria-labelledby="selection-${e(b.id)}" hidden><img src="assets/${e(b.image)}" width="1536" height="1024" alt="${e(b.alt)}" loading="lazy"><div><p class="eyebrow">${e(b.genre)}</p><h2 id="selection-${e(b.id)}">${e(b.title)}</h2><p>${e(b.description)}</p><div class="selection-actions"><a class="button" href="#${e(b.id)}">${e(c.explore.readMore)} <span aria-hidden="true">↓</span></a><button class="text-button" type="button" aria-haspopup="dialog" data-preview="${i}">${e(c.explore.peek)} <span aria-hidden="true">↗</span></button></div></div></section>`).join('')}</div>`;
const previewDialog = `<dialog class="book-preview" aria-label="${e(c.explore.previewLabel)}"><div class="preview-toolbar"><p class="eyebrow" data-preview-title></p><button class="text-button" type="button" data-preview-close autofocus>${e(c.explore.close)} ×</button></div><div class="preview-pages" tabindex="0" aria-label="${e(c.explore.previewLabel)}">${c.books.map((b,i)=>`<div data-preview-book="${i}" class="preview-book theme-${e(b.id)}" hidden>${[0,1,2].map(page=>`<section class="preview-spread" data-page="${page}" hidden><div class="preview-art"><img src="assets/${e(page===0?b.image:page===1?c.brandArt.podium.image:c.brandArt.mischief.image)}" width="1536" height="1024" alt="${e(page===0?b.alt:page===1?c.brandArt.podium.alt:c.brandArt.mischief.alt)}" loading="lazy"></div><div class="preview-copy"><p class="eyebrow">${e(c.explore.pageTitles[page])}</p>${page===0?`<h2>${e(b.title)}</h2><p>${e(b.description)}</p>`:page===1?`<h2>${e(b.personalization)}</h2><p>${e(c.how.steps[1].body)}</p>`:`<blockquote>${e(b.quote)}</blockquote><p>${e(c.how.steps[2].body)}</p>`}</div></section>`).join('')}</div>`).join('')}</div><div class="preview-controls"><button class="text-button" type="button" data-preview-prev>← ${e(c.explore.previous)}</button><p data-preview-status role="status" aria-live="polite" data-page-label="${e(c.explore.page)}" data-of-label="${e(c.explore.of)}"></p><button class="text-button" type="button" data-preview-next>${e(c.explore.next)} →</button></div></dialog>`;
// Frame only the selected lettering, preserving the original artwork pixels.
const wordmark = `<svg class="brand-logo" viewBox="582 249 1582 260" width="1582" height="260" role="img" aria-label="${e(c.brand)}" overflow="hidden"><image href="assets/wordmark-mischief.webp" width="2172" height="724" /></svg>`;
const favicon = 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="#33291f"/><path d="M5 8q6-2 11 2 5-4 11-2v17q-6-2-11 1-5-3-11-1z" fill="none" stroke="#edd3a0" stroke-width="2"/><path d="M16 10v16" stroke="#edd3a0" stroke-width="2"/></svg>');
const html = `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#eee5d4"><title>${e(c.title)}</title><meta name="description" content="${e(c.description)}"><meta property="og:title" content="${e(c.title)}"><meta property="og:description" content="${e(c.description)}"><meta property="og:type" content="website"><link rel="canonical" href="https://pathsofwonder.app/"><meta property="og:url" content="https://pathsofwonder.app/"><link rel="icon" href="${e(favicon)}"><link rel="preload" as="font" type="font/woff2" href="assets/fraunces-latin-400-normal.woff2" crossorigin><script>if ('animate' in Element.prototype && 'IntersectionObserver' in window) document.documentElement.classList.add('art-motion-supported');</script><link rel="stylesheet" href="${versioned('styles.css')}"><script src="${versioned('site.js')}" defer></script><script src="${versioned('art-motion.js')}" defer></script></head>
<body id="top"><a class="skip-link" href="#main">${e(c.skip)}</a><header class="header wrap"><a class="wordmark" href="#top">${wordmark}</a><nav aria-label="Main">${c.nav.map(n=>`<a href="${e(n.href)}">${e(n.label)}</a>`).join('')}</nav><a class="header-status" href="#testing">${e(c.launch.status)}</a></header>
<main id="main"><section class="hero wrap" aria-labelledby="hero-heading"><div class="hero-copy"><p class="eyebrow">${e(c.hero.eyebrow)}</p><h1 id="hero-heading">${e(c.hero.heading)} <em>${e(c.hero.emphasis)}</em></h1><p class="intro">${e(c.hero.body)}</p><div class="hero-actions"><a class="button" href="#books">${e(c.hero.cta)} <span aria-hidden="true">↓</span></a><span class="quiet">${e(c.hero.note)}</span></div></div>${doorArt}${worldPreview}</section>
<section id="books" class="library wrap section"><div class="section-intro">${sectionHeading(c.library.eyebrow,c.library.heading)}<p>${e(c.library.intro)}</p><nav class="book-links" aria-label="Books">${c.books.map(b=>`<a href="#${e(b.id)}"><span>${e(b.title)}</span><span aria-hidden="true">→</span></a>`).join('')}</nav></div><div class="library-art">${animatedArtwork("mischief", c, e)}</div></section>
<section id="how-it-works" class="how section"><div class="wrap how-layout"><div>${sectionHeading(c.how.eyebrow,c.how.heading)}<ol class="steps">${c.how.steps.map((s,i)=>`<li><span class="step-number" aria-hidden="true">0${i+1}</span><h3>${e(s.heading)}</h3><p>${e(s.body)}</p></li>`).join('')}</ol></div><div class="how-art">${animatedArtwork("podium", c, e)}</div></div></section>
<div class="stories">${c.books.map((b,i)=>`<article id="${e(b.id)}" class="story-world theme-${e(b.id)}" data-reveal><div class="world-decoration" aria-hidden="true"></div><div class="story wrap section"><div class="story-art">${art(b)}</div><div class="story-copy"><p class="eyebrow">${e(b.genre)}</p><h2>${e(b.title)}</h2><p>${e(b.description)}</p><p class="personalization"><span aria-hidden="true">✧</span> ${e(b.personalization)}</p><button class="preview-trigger" type="button" aria-haspopup="dialog" data-preview="${i}" hidden>${e(c.explore.peek)} <span aria-hidden="true">↗</span></button></div><blockquote class="story-quote">${e(b.quote)}</blockquote></div></article>`).join('')}</div>
<section class="reasons section"><div class="wrap reasons-layout"><div>${sectionHeading(c.reasons.eyebrow,c.reasons.heading)}${companionArt("tinkerers")}</div><div class="reason-grid">${c.reasons.items.map(i=>`<div><h3>${e(i.heading)}</h3><p>${e(i.body)}</p></div>`).join('')}</div></div></section>
<section id="parents" class="parents section wrap"><div>${sectionHeading(c.parents.eyebrow,c.parents.heading)}<p>${e(c.parents.body)}</p><div class="reading-together"><h3>${e(c.parents.aside)}</h3><p>${e(c.parents.asideBody)}</p></div></div>${companionArt("readers")}</section>
<section class="faq section wrap" aria-labelledby="faq-heading"><h2 id="faq-heading">${e(c.faq.heading)}</h2><div>${c.faq.items.map(f=>`<details><summary>${e(f.question)}<span aria-hidden="true">＋</span></summary><p>${e(f.answer)}</p></details>`).join('')}</div></section>
<section id="our-story" class="about wrap">${companionArt("creators")}<div class="about-copy"><p class="eyebrow">${e(c.about.heading)}</p><p>${e(c.about.body)}</p></div></section>
<section id="testing" class="launch section"><div class="wrap"><h2 class="launch-heading" aria-label="${e(c.launch.heading)}">${e(c.launch.heading).replace(e(c.launch.highlight), `<span class="launch-path">${companionArt("sprite", true, true)}<span class="launch-path-word">${e(c.launch.highlight)}</span></span>`)}</h2><p class="launch-intro">${e(c.launch.body)}</p><p class="testing-status">${e(c.launch.status)}</p><p class="launch-detail">${e(c.launch.detail)}</p><a href="#books">${e(c.launch.back)} <span aria-hidden="true">↑</span></a></div></section></main>
<footer class="footer wrap"><div><a class="wordmark" href="#top">${wordmark}</a><p>${e(c.footer.note)}</p></div><p>${e(c.footer.copyright)}</p><a href="#top">${e(c.footer.top)} ↑</a><button type="button" class="motion-toggle" data-motion data-pause="${e(c.explore.pause)}" data-resume="${e(c.explore.resume)}" hidden>${e(c.explore.pause)}</button></footer>
<dialog class="viewer" aria-label="${e(c.library.artLabel)}"><div class="viewer-toolbar"><button type="button" data-zoom data-zoom-in="${e(c.library.zoom)}" data-zoom-out="${e(c.library.zoomOut)}">${e(c.library.zoom)}</button><button type="button" data-close autofocus>${e(c.library.close)} ×</button></div><div class="viewer-canvas"><img alt=""></div></dialog>
${previewDialog}
</body></html>`;
writeFileSync(path.join(root,'dist/index.html'), html);
console.log('Built marketing/dist/index.html from ui_copy.json');
