import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const c = JSON.parse(readFileSync(path.join(root, 'ui_copy.json'), 'utf8'));
const e = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const sectionHeading = (eyebrow, heading) => `<p class="eyebrow">${e(eyebrow)}</p><h2>${e(heading)}</h2>`;
const art = (b, eager = false) => `<a class="art-link" href="assets/${e(b.image)}" data-art aria-label="${e(c.library.artLabel)}: ${e(b.title)}"><img src="assets/${e(b.image)}" alt="${e(b.alt)}" width="1536" height="1024" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'}><span class="art-hint">${e(c.library.artLabel)} <span aria-hidden="true">＋</span></span></a>`;
const favicon = 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="#33291f"/><path d="M5 8q6-2 11 2 5-4 11-2v17q-6-2-11 1-5-3-11-1z" fill="none" stroke="#edd3a0" stroke-width="2"/><path d="M16 10v16" stroke="#edd3a0" stroke-width="2"/></svg>');
const html = `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#eee5d4"><title>${e(c.title)}</title><meta name="description" content="${e(c.description)}"><meta property="og:title" content="${e(c.title)}"><meta property="og:description" content="${e(c.description)}"><meta property="og:type" content="website"><link rel="icon" href="${e(favicon)}"><link rel="preload" as="font" type="font/woff2" href="assets/fraunces-latin-400-normal.woff2" crossorigin><link rel="stylesheet" href="styles.css"><script src="site.js" defer></script></head>
<body id="top"><a class="skip-link" href="#main">${e(c.skip)}</a><header class="header wrap"><a class="wordmark" href="#top"><img class="brand-logo" src="assets/paths-of-wonder-logo-v2.png" width="2172" height="724" alt="${e(c.brand)}"></a><nav aria-label="Main">${c.nav.map(n=>`<a href="${e(n.href)}">${e(n.label)}</a>`).join('')}</nav><a class="header-status" href="#testing">${e(c.launch.status)}</a></header>
<main id="main"><section class="hero wrap" aria-labelledby="hero-heading"><div class="hero-copy"><p class="eyebrow">${e(c.hero.eyebrow)}</p><h1 id="hero-heading">${e(c.hero.heading)} <em>${e(c.hero.emphasis)}</em></h1><p class="intro">${e(c.hero.body)}</p><div class="hero-actions"><a class="button" href="#books">${e(c.hero.cta)} <span aria-hidden="true">↓</span></a><span class="quiet">${e(c.hero.note)}</span></div></div><figure class="hero-art">${art(c.books[1], true)}<figcaption>${e(c.hero.caption)}</figcaption></figure></section>
<section id="books" class="library wrap section"><div class="section-intro">${sectionHeading(c.library.eyebrow,c.library.heading)}<p>${e(c.library.intro)}</p></div><nav class="book-stack" aria-label="Books">${c.books.map((b,i)=>`<a class="book-spine book-${i}" href="#${e(b.id)}"><span class="volume" aria-hidden="true">0${i+1}</span><span><span class="book-title">${e(b.title)}</span><span class="book-genre">${e(b.genre)}</span></span><span class="ornament" aria-hidden="true">✧</span></a>`).join('')}</nav></section>
<section id="how-it-works" class="how section"><div class="wrap">${sectionHeading(c.how.eyebrow,c.how.heading)}<ol class="steps">${c.how.steps.map((s,i)=>`<li><span class="step-number" aria-hidden="true">0${i+1}</span><h3>${e(s.heading)}</h3><p>${e(s.body)}</p></li>`).join('')}</ol></div></section>
<div class="stories wrap">${c.books.map((b,i)=>`<article id="${e(b.id)}" class="story section"><div class="story-art">${art(b)}</div><div class="story-copy"><p class="eyebrow">${e(b.genre)}</p><h2>${e(b.title)}</h2><p>${e(b.description)}</p><p class="personalization"><span aria-hidden="true">✧</span> ${e(b.personalization)}</p><blockquote>${e(b.quote)}</blockquote></div></article>`).join('')}</div>
<section class="reasons section"><div class="wrap reasons-layout"><div>${sectionHeading(c.reasons.eyebrow,c.reasons.heading)}</div><div class="reason-grid">${c.reasons.items.map(i=>`<div><h3>${e(i.heading)}</h3><p>${e(i.body)}</p></div>`).join('')}</div></div></section>
<section id="parents" class="parents section wrap"><div>${sectionHeading(c.parents.eyebrow,c.parents.heading)}<p>${e(c.parents.body)}</p></div><aside><span class="ornament" aria-hidden="true">✧</span><h3>${e(c.parents.aside)}</h3><p>${e(c.parents.asideBody)}</p></aside></section>
<section class="faq section wrap" aria-labelledby="faq-heading"><h2 id="faq-heading">${e(c.faq.heading)}</h2><div>${c.faq.items.map(f=>`<details><summary>${e(f.question)}<span aria-hidden="true">＋</span></summary><p>${e(f.answer)}</p></details>`).join('')}</div></section>
<section class="about wrap"><p class="eyebrow">${e(c.about.heading)}</p><p>${e(c.about.body)}</p></section>
<section id="testing" class="launch section"><div class="wrap">${sectionHeading(c.launch.eyebrow,c.launch.heading)}<p class="launch-intro">${e(c.launch.body)}</p><p class="testing-status">${e(c.launch.status)}</p><p class="launch-detail">${e(c.launch.detail)}</p><a href="#books">${e(c.launch.back)} <span aria-hidden="true">↑</span></a></div></section></main>
<footer class="footer wrap"><div><a class="wordmark" href="#top">${e(c.brand)}</a><p>${e(c.footer.note)}</p></div><p>${e(c.footer.copyright)}</p><a href="#top">${e(c.footer.top)} ↑</a></footer>
<dialog class="viewer" aria-label="${e(c.library.artLabel)}"><div class="viewer-toolbar"><button type="button" data-zoom data-zoom-in="${e(c.library.zoom)}" data-zoom-out="${e(c.library.zoomOut)}">${e(c.library.zoom)}</button><button type="button" data-close autofocus>${e(c.library.close)} ×</button></div><div class="viewer-canvas"><img alt=""></div></dialog>
</body></html>`;
writeFileSync(path.join(root,'dist/index.html'), html);
console.log('Built marketing/dist/index.html from ui_copy.json');
